
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd web
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
     commands:
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
      - ../appspec.yml
      - ../scripts/**/*
  base-directory: 'web/dist*'
  discard-paths: yes